services:
  app:
    container_name: ai-server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
           - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - LOG_DIR=/app/logs
      - SECRET_KEY=${SECRET_KEY}
      - CREDENTIALS=true
      - ORIGIN=https://ai-server-production-production-8e2d.up.railway.app
      - LOG_FORMAT=combined
      # ✅ INNGEST VARIABLES FOR PRODUCTION:
      - INNGEST_SIGNING_KEY=${INNGEST_SIGNING_KEY}
      - INNGEST_EVENT_KEY=${INNGEST_EVENT_KEY}
      - INNGEST_APP_URL=https://ai-server-production-production-8e2d.up.railway.app
    volumes:
      - ./persistent_uploads:/app/dist/uploads
      - ./logs:/app/logs
    restart: always

  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - '91:91'
      - '9443:9443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    environment:
      - DOMAIN=ai-server-u14194.vm.elestio.app
    depends_on:
      - app
    restart: always
