[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.testing]
[environments.testing.build]
watchPatterns = ["src/**/*", "package.json", "tsconfig.json"]

[environments.testing.deploy]
healthcheckPath = "/health"

[environments.production]
[environments.production.build]
watchPatterns = ["src/**/*", "package.json", "tsconfig.json"]

[environments.production.deploy]
healthcheckPath = "/health"

# Переменные для тестового окружения (main branch)
[environments.testing.variables]
NODE_ENV = "testing"
APP_ENV = "testing"
PORT = "${{ PORT }}"
LOG_DIR = "/tmp/ai-server-logs"
RAILWAY_HEALTHCHECK_TIMEOUT_SEC = "300"

# Переменные для продакшн окружения (production branch)  
[environments.production.variables]
NODE_ENV = "production"
APP_ENV = "production" 
PORT = "${{ PORT }}"
LOG_DIR = "/tmp/ai-server-logs"
RAILWAY_HEALTHCHECK_TIMEOUT_SEC = "300"
