[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.staging]
[environments.staging.build]
watchPatterns = ["src/**/*", "package.json", "tsconfig.json"]

[environments.staging.deploy]
healthcheckPath = "/health"

[environments.production]
[environments.production.build]
watchPatterns = ["src/**/*", "package.json", "tsconfig.json"]

[environments.production.deploy]
healthcheckPath = "/health"

# Переменные для тестового окружения (main branch)
[environments.staging.variables]
NODE_ENV = "production"
APP_ENV = "staging"
PORT = "${{ PORT }}"

# Переменные для продакшн окружения (production branch)  
[environments.production.variables]
NODE_ENV = "production"
APP_ENV = "production" 
PORT = "${{ PORT }}"