#!/bin/bash

echo "🚀 Starting AI Server in Development Mode"
echo ""
echo "Available commands:"
echo "  npm run dev          - Main server with auto-reload (nodemon)"
echo "  npm run dev:server   - Main server (single run)"  
echo "  npm run dev:inngest  - Inngest dev server (port 8289)"
echo "  npm run dev:mcp      - MCP server for Claude"
echo ""
echo "📋 Logs:"
echo "  npm run logs:clean   - Clean filtered logs"
echo "  npm run logs:errors  - Only errors"
echo "  npm run logs:api     - API requests only"
echo ""
echo "🔧 Recommended development flow:"
echo ""
echo "Terminal 1: npm run dev          # Main server"
echo "Terminal 2: npm run dev:inngest  # Inngest (if needed)"
echo "Terminal 3: npm run dev:mcp      # MCP (if needed)"
echo ""
echo "✅ No PM2 needed - each service in separate terminal"
echo "✅ Full control and visibility of each service"
echo "✅ Easy debugging and log monitoring"